### ISSUE TITLE
issues with primary-key/id not named 'id'

### ISSUE THREAD

**Issue by tony-kerz** [josx/aor-feathers-client#30]
hi,

i have a sequelize model where the primary key is not named 'id':
```
export default function(sequelize, DataTypes) {
  return sequelize.define(
    'User',
    {
      username: {
        type: DataTypes.STRING,
        primaryKey: true
      },
//...
```

`feathers-sequelize` allows you to specify the id field, something like:
```
app.use(path, feathersSqlzService({Model, paginate, id: 'username'}))
```

this seems to work fine at the rest level:
```
http://localhost:3000/users/user-1
```
will yield:
```
{
  username: "user-1",
  //...
  createdAt: "2017-07-27T12:10:19.000Z",
  updatedAt: "2017-07-27T12:10:19.000Z"
}
```
so seems ok to that point, but when admin-on-rest attempts to display the user list with two users in the database, i get:
- the first user repeated twice
- the second user not listed
- the following warning in the browser:
```
Each child in an array or iterator should have a unique "key" prop. Check the render method of `DatagridBody`.
```

i poked around [here](https://github.com/josx/aor-feathers-client/blob/master/src/restClient.js) with some `console.log` statements in the browser, but nothing obvious popped out at me.

any ideas what might be going wrong?

**Comment by josx** [comment]
In the last release https://github.com/josx/aor-feathers-client/releases/tag/v0.4.0 we added the custom id support.

Are you using that version?

The admin on rest file might be like this:

```js
const options = { id: 'username' };
const App = () => (
  <Admin
    authClient={authClient(feathersClient, authClientOptions)}
    restClient={restClient(feathersClient, options)}
  >
    <Resource name="users" list={UserList} />
  </Admin>
);
```

**Comment by tony-kerz** [comment]
hi @josx,

thanks for the quick response!

actually, specifying `{id: 'username'}` helps with the `User` resource, but i have several other resources that still use `id` as a primary-key, and it messed with them.

wouldn't i need a way to specify `{id: 'username'}` for only a specific resource?

best,
tony.

**Comment by josx** [comment]
You are right, by now only support one type or id for all resources.
Can you add that feature?

**Comment by tony-kerz** [comment]
[this](https://github.com/tony-kerz/aor-feathers-client/blob/tk/id/src/restClient.js) seems to work ok.

configuration would be like:
```
const options = {'ftp-users': {id: 'username'}}

const App = () =>
  <Admin
    title="Universal Data Exchange Administration"
    dashboard={Dashboard}
    restClient={restClient(feathersClient, options)}
    authClient={authClient}
  >
```
but would still support something like below for cases where desired effect is to replace `id` for all resources:
```
const options = {id: '_id'}

const App = () =>
  <Admin
    title="Universal Data Exchange Administration"
    dashboard={Dashboard}
    restClient={restClient(feathersClient, options)}
    authClient={authClient}
  >
```
if it looks ok to you, i can clean it up:
- remove `console.log` messages
> would you consider allowing [`debug`](https://github.com/visionmedia/debug) as a dependency as it is also used by feathers anyway?
- add a test or two

> i wasn't sure exactly how to work with your publish strategy, so i just removed `lib` from `.gitignore` and pushed the results of a local `yarn run build` to my github fork for testing. is that something you would want p/r submitters to work with, or would you handle that post merge?

regards,
tony.

**Comment by josx** [comment]
* Your configuration is ok to me, also the backwards support syntax.
* Would be great to use debug instead of console.log
* We need to test custom id feature (we dont have any test on that)
*  Build is using [Make](https://github.com/josx/aor-feathers-client/blob/master/Makefile) and babel to transform code. (So in the project we dont need to push lib dir)

Thanks,  I will be watining for your PR ;)

**Comment by josx** [comment]
@tony-kerz do you need help on this?

**Comment by tony-kerz** [comment]
hi jose,

sorry for the delay, i got pulled away on other stuff, but i am just looking into the tests now.

i'm sure i'm doing something stupid, but when i run:

```
npm run test
```
i get:
```
❰a716948❙~/git/aor-feathers-client(git✱tk/id)❱✘≻ npm run test                                               [11d8h45m] M

> aor-feathers-client@0.4.0 pretest /Users/tony/git/aor-feathers-client
> npm run build


> aor-feathers-client@0.4.0 build /Users/tony/git/aor-feathers-client
> make build

src/authClient.js -> lib/authClient.js
src/index.js -> lib/index.js
src/restClient.js -> lib/restClient.js

> aor-feathers-client@0.4.0 test /Users/tony/git/aor-feathers-client
> npm run coverage


> aor-feathers-client@0.4.0 coverage /Users/tony/git/aor-feathers-client
> istanbul cover node_modules/mocha/bin/_mocha -- --opts mocha.opts



  Rest Client
    when called with GET_MANY
      1) "before each" hook for "calls the client's find method"
    when called with GET_LIST
      2) "before each" hook for "calls the client's find method"
    when called with GET_ONE
      3) "before each" hook for "calls the client's get method with the id in params"
    when called with UPDATE
      4) "before each" hook for "calls the client's update method with the id and data in params"
    when called with CREATE
      5) "before each" hook for "calls the client's create method with the data in params"
    when called with DELETE
      6) "before each" hook for "calls the client's remove method with the id in params"
    when called with an invalid type
      ✓ should throw an error


  1 passing (13ms)
  6 failing

  1) Rest Client when called with GET_MANY "before each" hook for "calls the client's find method":
     TypeError: Cannot read property 'posts' of undefined
      at getIdKey (lib/restClient.js:9:1700)
      at mapRequest (lib/restClient.js:9:2183)
      at lib/restClient.js:9:6872
      at Context.<anonymous> (test/restClient.spec.js:50:21)

  2) Rest Client when called with GET_LIST "before each" hook for "calls the client's find method":
     TypeError: Cannot read property 'posts' of undefined
      at getIdKey (lib/restClient.js:9:1700)
      at mapRequest (lib/restClient.js:9:2183)
      at lib/restClient.js:9:6872
      at Context.<anonymous> (test/restClient.spec.js:94:21)

  3) Rest Client when called with GET_ONE "before each" hook for "calls the client's get method with the id in params":
     TypeError: Cannot read property 'posts' of undefined
      at getIdKey (lib/restClient.js:9:1700)
      at mapRequest (lib/restClient.js:9:2183)
      at lib/restClient.js:9:6872
      at Context.<anonymous> (test/restClient.spec.js:175:21)

  4) Rest Client when called with UPDATE "before each" hook for "calls the client's update method with the id and data in params":
     TypeError: Cannot read property 'posts' of undefined
      at getIdKey (lib/restClient.js:9:1700)
      at mapRequest (lib/restClient.js:9:2183)
      at lib/restClient.js:9:6872
      at Context.<anonymous> (test/restClient.spec.js:201:21)

  5) Rest Client when called with CREATE "before each" hook for "calls the client's create method with the data in params":
     TypeError: Cannot read property 'posts' of undefined
      at getIdKey (lib/restClient.js:9:1700)
      at mapRequest (lib/restClient.js:9:2183)
      at lib/restClient.js:9:6872
      at Context.<anonymous> (test/restClient.spec.js:226:21)

  6) Rest Client when called with DELETE "before each" hook for "calls the client's remove method with the id in params":
     TypeError: Cannot read property 'posts' of undefined
      at getIdKey (lib/restClient.js:9:1700)
      at mapRequest (lib/restClient.js:9:2183)
      at lib/restClient.js:9:6872
      at Context.<anonymous> (test/restClient.spec.js:247:21)



=============================================================================
Writing coverage object [/Users/tony/git/aor-feathers-client/coverage/coverage.json]
Writing coverage reports at [/Users/tony/git/aor-feathers-client/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 36.26% ( 33/91 )
Branches     : 14.52% ( 9/62 )
Functions    : 46.15% ( 6/13 )
Lines        : 40.26% ( 31/77 )
================================================================================
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! aor-feathers-client@0.4.0 coverage: `istanbul cover node_modules/mocha/bin/_mocha -- --opts mocha.opts`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the aor-feathers-client@0.4.0 coverage script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tony/.npm/_logs/2017-08-09T21_09_51_131Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! aor-feathers-client@0.4.0 test: `npm run coverage`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the aor-feathers-client@0.4.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tony/.npm/_logs/2017-08-09T21_09_51_145Z-debug.log
```

can u spot anything obvious i'm doing wrong? 
this is basically attempting to run the tests unchanged.
let me know if i can provide any significant info on my local environment...

**Comment by tony-kerz** [comment]
sorry jose, i got distracted with some other stuff, you kno the deal, but how's [this](https://github.com/josx/aor-feathers-client/pull/33)?

**Comment by josx** [comment]
great! merged
